### ISSUE TITLE
Tests error

### ISSUE THREAD

**Issue by yoavram** [eyurtsev/FlowCytometryTools#1]
Tests fail on Windows 7, Python 2.7, FlowCytomeryTools from master branch 19 May 2015:
```
>>> nosetests
======================================================================
ERROR: Failure: ImportError (No module named flowcytometrytools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\nose\loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Anaconda\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Anaconda\lib\site-packages\nose\importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named flowcytometrytools


-----------------------------------------------------------------------------
1) ERROR: Failure: ImportError (No module named flowcytometrytools)

   Traceback (most recent call last):
    C:\Anaconda\lib\site-packages\nose\loader.py line 420 in loadTestsFromName
      addr.filename, addr.module)
    C:\Anaconda\lib\site-packages\nose\importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    C:\Anaconda\lib\site-packages\nose\importer.py line 79 in importFromDir
      fh, filename, desc = find_module(part, path)
   ImportError: No module named flowcytometrytools
```

**Comment by eyurtsev** [comment]
nosetests are passing for me locally after this commit:

https://github.com/eyurtsev/FlowCytometryTools/commit/41160e87d39109ab3615eca4840b85b32bc9ae84

However, it looks like the import error arises because the name of the package FlowCytometryTools has been lower-cased... I may need to look into it a bit more...

**Comment by yoavram** [comment]
OK, commit 41160e8 works for me.
I created a conda [environment.yml](https://gist.github.com/yoavram/e2b76f942e73aacd1014) to reproduce a working environment. Thanks.
