### ISSUE TITLE
IntervalGate bug(?)

### ISSUE THREAD

**Issue by alonyan** [eyurtsev/FlowCytometryTools#15]
I've been using your Flow package to do some batch processing. It's awesome. Thanks!

Anyway, I think there's a small bug in the _identify function for interval gates. At least in my hands, applying an interval gate always returned an error.

fix:

I edited gates.py, line 237, to:

```
def _identify(self, dataframe):

    idx = (dataframe[self.channels[0]] <= self.vert[1]) & (dataframe[self.channels[0]] >= self.vert[0])

    if self.region == 'out':
        idx = ~idx

    return idx
```

And then it works fine. 

All the best, and thanks again!

**Comment by eyurtsev** [comment]
This code looks identical to the current code on master in terms, so I'm not sure why you'd be seeing a difference. Would you be able to send a traceback with the error, so I could write unit test for that?

**Comment by eyurtsev** [comment]
Added tests for interval gate:

https://github.com/eyurtsev/FlowCytometryTools/commit/d1e2dcbbae807abdebb228e161db90a7a4df7568

All edge cases seem to be handled correctly

**Comment by alonyan** [comment]
`Traceback (most recent call last):

  File "<ipython-input-5-b315b5adb803>", line 2, in <module>
    MFItableCals = Standards.gate(gates[0]).geoMeans()['PE-A']

  File "FlowAnalysis/LoadFlowSamples_v2.py", line 109, in gate
    gated.samples = _gate(gated.samples, gate1)

  File "FlowAnalysis/LoadFlowSamples_v2.py", line 129, in _gate
    Gatedsamples[i] = samples[i].gate(gate1)

  File "<decorator-gen-126>", line 2, in gate

  File "/Users/Alonyan/anaconda/envs/FCSenv/lib/python2.7/site-packages/FlowCytometryTools/core/bases.py", line 105, in queueable
    out = fun(*args, **kwargs)

  File "/Users/Alonyan/anaconda/envs/FCSenv/lib/python2.7/site-packages/FlowCytometryTools/core/containers.py", line 394, in gate
    newdata = gate(data)

  File "/Users/Alonyan/anaconda/envs/FCSenv/lib/python2.7/site-packages/FlowCytometryTools/core/gates.py", line 120, in __call__
    idx = self._identify(dataframe)

  File "/Users/Alonyan/anaconda/envs/FCSenv/lib/python2.7/site-packages/FlowCytometryTools/core/gates.py", line 241, in _identify
    idx1 = self.vert[0] <= dataframe[self.channels[0]]

  File "/Users/Alonyan/anaconda/envs/FCSenv/lib/python2.7/site-packages/pandas/core/ops.py", line 741, in wrapper
    if len(self) != len(other):

TypeError: len() of unsized object`

It does seem weird that this returns a bug, and what I wrote - which basically looks to be doing the same thing - isn't. Not sure what's going on here...

**Comment by alonyan** [comment]
Changing 
`idx1 = self.vert[0] <= dataframe[self.channels[0]]`
to
`dataframe[self.channels[0]]>=idx1 = self.vert[0] `

also (bizarrely) seems to solve my problem. I'm not exactly sure what's going on though since this shouldn't matter. Weird.

**Comment by alonyan** [comment]
And, it's a bug with pandas:
[multiple dispatch problem when comparing pandas Series against numpy scalars](https://github.com/pandas-dev/pandas/issues/14262)

**Comment by eyurtsev** [comment]
Thanks for looking into this... Applied your patch hopefully it solves the issue :)

https://github.com/eyurtsev/FlowCytometryTools/commit/a3c0b4a79d6352b8864caeda87a8340ba2f793a7
