### ISSUE TITLE
collections.MutableMapping has been moved from the collections module to collections.abc

### ISSUE THREAD

**Issue by aptagood** [eyurtsev/FlowCytometryTools#44]
Looks like version 0.51 does not have the updated bases.py regarding the addition of collections.abc 

import FlowCytometryTools as fct
Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    import FlowCytometryTools as fct
  File "/Users/apta/Library/Python/3.11/lib/python/site-packages/FlowCytometryTools/__init__.py", line 8, in <module>
    from FlowCytometryTools.core.containers import (FCMeasurement, FCCollection, FCOrderedCollection,
  File "/Users/apta/Library/Python/3.11/lib/python/site-packages/FlowCytometryTools/core/containers.py", line 15, in <module>
    from FlowCytometryTools.core.bases import (Measurement, MeasurementCollection, OrderedCollection,
  File "/Users/apta/Library/Python/3.11/lib/python/site-packages/FlowCytometryTools/core/bases.py", line 356, in <module>
    class MeasurementCollection(collections.MutableMapping, BaseObject):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by aptagood** [comment]
This error occurs because in Python 3.10 and later, collections.MutableMapping has been moved from the collections module to collections.abc. The FlowCytometryTools package you're using is importing MutableMapping from the old location, which causes an AttributeError in newer Python versions.

This is a compatibility issue with the current version of FlowCytometryTools and Python 3.10+.

Why the Error Happens
In Python 3.3–3.9: collections.MutableMapping was deprecated, but still available.

In Python 3.10+: You have to use collections.abc.MutableMapping instead.
